"""Single-source contract for committed `.env.example`.

Research key names stay owned by ``RESEARCH_API_KEY_NAMES`` in
``lane_capability_enforcement.py``. MCP env names stay owned by the ``MCPS=()``
array in ``scripts/bootstrap-mcps.sh``. Runtime/path names that have no other
home are listed here once.

``.env.example`` is generated from that union so it cannot drift.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from lane_capability_enforcement import RESEARCH_API_KEY_NAMES


ROOT = Path(__file__).resolve().parents[2]
BOOTSTRAP = ROOT / "scripts" / "bootstrap-mcps.sh"
ENV_EXAMPLE = ROOT / ".env.example"

ROW_RE = re.compile(
    r'^\s*"(?P<name>[a-z-]+)\|(?P<rest>[^"]*)"\s*$',
    re.MULTILINE,
)
ENV_FIELD_RE = re.compile(r"^[A-Z][A-Z0-9_]*( [A-Z][A-Z0-9_]*)*$")

# Path / runtime names that no other file owns. Do not restate research or
# MCP credential names here — they are derived from their owners.
RUNTIME_ENV_NAMES = (
    "CHRONO_VAULT_ROOT",
    "VAULT_ROOT",
    "SQUAD_SESSION",
    "SQUAD_DAEMON_MODE",
    "SQUAD_SECRETS_DIR",
    "SQUAD_ENV_FILE",
    "VIBESQUAD_DAEMON_TOKEN",
    "CHRONO_VAULT_BROKER_TOKEN",
    "SQUAD_CI_HOST_INDEPENDENT",
    "SQUAD_SKIP_DOCTOR",
)

HEADER = """# Vibe Squad environment contract. Values empty on purpose.
#
# Copy to `.env` (gitignored) or inject via Compose `environment:` / Azure Key
# Vault. Load order is owned by shared/load-secrets.sh: process env, then
# SQUAD_SECRETS_DIR (default /run/secrets), then SQUAD_ENV_FILE (default
# /config/.env then repo .env), then legacy ~/.config/shell/secrets.zsh.
#
# Model lanes stay native-CLI OAuth. These API keys never authenticate
# `claude`, `codex`, `agy`, or `kimi`. See docs/install/provider-clis.md.
#
# Generated by scripts/python/squad_env_contract.py. Do not add names by hand;
# add them to RESEARCH_API_KEY_NAMES, scripts/bootstrap-mcps.sh MCPS, or
# RUNTIME_ENV_NAMES in this module, then re-run:
#   python3 scripts/python/squad_env_contract.py --write
#
"""

SECTIONS = (
    (
        "Paths and runtime",
        (
            "CHRONO_VAULT_ROOT",
            "VAULT_ROOT",
            "SQUAD_SESSION",
            "SQUAD_DAEMON_MODE",
            "SQUAD_SECRETS_DIR",
            "SQUAD_ENV_FILE",
        ),
    ),
    (
        "Daemon",
        ("VIBESQUAD_DAEMON_TOKEN",),
    ),
    (
        "Vault / Obsidian",
        (
            "CHRONO_VAULT_BROKER_TOKEN",
            "OBSIDIAN_REST_API_KEY",
            "OBSIDIAN_VAULT_ROOT",
        ),
    ),
    (
        "Optional MCP / research keys",
        (
            "XAI_API_KEY",
            "PERPLEXITY_API_KEY",
            "FIRECRAWL_API_KEY",
            "GEMINI_API_KEY",
            "OPENAI_API_KEY",
        ),
    ),
    (
        "Image / CI",
        (
            "SQUAD_CI_HOST_INDEPENDENT",
            "SQUAD_SKIP_DOCTOR",
        ),
    ),
)


def bootstrap_mcp_env_names() -> frozenset[str]:
    """Env names declared by the MCPS array in scripts/bootstrap-mcps.sh."""
    names: set[str] = set()
    for row in ROW_RE.finditer(BOOTSTRAP.read_text(encoding="utf-8")):
        env = row.group("rest").rsplit("|", 1)[-1]
        if not ENV_FIELD_RE.match(env):
            continue
        names.update(env.split())
    return frozenset(names)


def expected_env_names() -> tuple[str, ...]:
    """Union of runtime names, research keys, and bootstrap MCP env names."""
    names = set(RUNTIME_ENV_NAMES)
    names.update(RESEARCH_API_KEY_NAMES)
    names.update(bootstrap_mcp_env_names())
    return tuple(sorted(names))


def parse_example_names(text: str) -> tuple[str, ...]:
    found: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        name = stripped.split("=", 1)[0].strip()
        if name:
            found.append(name)
    return tuple(found)


def render_env_example() -> str:
    expected = set(expected_env_names())
    lines = [HEADER.rstrip(), ""]
    seen: set[str] = set()
    for title, names in SECTIONS:
        lines.append(f"# {title}")
        for name in names:
            lines.append(f"{name}=")
            seen.add(name)
        lines.append("")
    extra = sorted(expected - seen)
    if extra:
        lines.append("# Additional names owned by bootstrap / research tuple")
        for name in extra:
            lines.append(f"{name}=")
        lines.append("")
    missing_from_expected = seen - expected
    if missing_from_expected:
        raise AssertionError(
            "section names not in the derived union: "
            + ", ".join(sorted(missing_from_expected))
        )
    return "\n".join(lines).rstrip() + "\n"


def validate_env_example(path: Path = ENV_EXAMPLE) -> None:
    if not path.is_file():
        raise AssertionError(f"{path} is missing")
    actual = set(parse_example_names(path.read_text(encoding="utf-8")))
    expected = set(expected_env_names())
    if actual != expected:
        raise AssertionError(
            f"{path.name} names {sorted(actual)} != derived union {sorted(expected)}"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite .env.example from the owning lists",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if .env.example has drifted",
    )
    args = parser.parse_args(argv)
    if args.write:
        ENV_EXAMPLE.write_text(render_env_example(), encoding="utf-8")
        print(f"wrote {ENV_EXAMPLE}")
        return 0
    if args.check:
        validate_env_example()
        print(f"{ENV_EXAMPLE.name} matches the owning lists")
        return 0
    parser.print_help()
    return 64


if __name__ == "__main__":
    raise SystemExit(main())
