[package]
name = "tss-bridge-fuzz-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }
tss-bridge-fuzz-rig = { path = "../rig" }
target-svm-gateway = { path = "../targets/svm-gateway" }

[[bin]]
name = "tss_bridge"
path = "fuzz_targets/tss_bridge.rs"
test = false
doc = false
bench = false

[workspace]
