#!/usr/bin/env python3
"""Generate the routing-map data block from the canonical specialist TSV.

The page's stylesheet is deliberately static: presentation is not a routing
fact and cannot be derived from the TSV. Everything between the generated
markers in ``docs/routing-map.html`` is owned by this program, including the
summary counts, lane distribution, routing rows, and explanatory notes whose
wording depends on current bindings. The accepted routing lanes and their
primary-default policy come from ``shared/lane-policy.tsv``.

    python3 tools/export/build_routing_map.py [--check]

``--check`` renders in memory and compares without writing, exiting non-zero
when the committed page is stale. This is the same generate/check contract used
by ``build_public_capability_cards.py``.
"""

from __future__ import annotations

import argparse
import csv
import html
import json
import os
import re
import sys
import tempfile
from collections import Counter
from pathlib import Path


SOURCE = Path("shared/specialist-runtime-map.tsv")
LANE_POLICY = Path("shared/lane-policy.tsv")
OUTPUT = Path("docs/routing-map.html")

BEGIN_MARKER = "<!-- BEGIN GENERATED ROUTING MAP -->"
END_MARKER = "<!-- END GENERATED ROUTING MAP -->"

REQUIRED_COLUMNS = {
    "specialist",
    "source_namespace",
    "capability_class",
    "safety_level",
    "primary_lane",
    "backup_lane",
    "escalate_lane",
    "review_lane",
}

NAMESPACE_ORDER = ("coding", "content", "security", "research", "shared", "sysmgmt")

TOKEN = re.compile(r"^[a-z0-9][a-z0-9_-]*$")

BODY_TEMPLATE = """<!-- Generated by tools/export/build_routing_map.py from shared/specialist-runtime-map.tsv. Do not hand-edit this block. -->
<main class="routing-map" aria-labelledby="routing-title">
  <header>
    <p class="eyebrow">Vibe Squad · Control-plane reference</p>
    <h1 id="routing-title">Specialist routing map</h1>
    <p class="subtitle">A scan-first reference for @@TOTAL@@ role-based specialists: primary execution CLI, manually selected cross-family backup, and independent review CLI. Each specialist binds its own model — the CLI is a vehicle, not a standing lane.</p>
    <div class="header-meta" aria-label="Map summary">
      <span class="meta-pill">@@TOTAL@@ specialists</span>
      <span class="meta-pill">@@NAMESPACE_COUNT@@ namespaces</span>
      <span class="meta-pill">@@LANE_COUNT@@ CLI vehicles</span>
      <span class="meta-pill">Generated · CI drift-checked</span>
    </div>
  </header>

  <section class="overview" aria-label="CLI legend and coordinator">
    <div class="panel legend-panel">
      <p class="panel-label">CLI vehicles</p>
      <div class="lane-grid">
@@LANE_CARDS@@
      </div>
      <p class="panel-label">Exact model, effort, and flags resolve per specialist through <code>shared/registries/profiles.tsv</code>; no CLI is pinned to one model.</p>
    </div>
    <aside class="panel chrono-card" aria-label="Chrono coordinator">
      <div>
        <span class="chrono-mark" aria-hidden="true">C</span>
        <h2>Chrono coordinates</h2>
        <p>Operator-facing orchestration sits above every specialist; Chrono is not a routable specialist. Each specialist below runs as a fresh CLI in its own git worktree, spawned per task.</p>
      </div>
      <code class="model-id">Claude Code</code>
    </aside>
  </section>

  <section class="panel distribution" aria-labelledby="distribution-title">
    <div class="distribution-head">
      <strong id="distribution-title">Primary-lane distribution</strong>
      <span>@@TOTAL@@ total assignments</span>
    </div>
    <div class="bar" role="img" aria-label="@@DISTRIBUTION_LABEL@@">
@@DISTRIBUTION_SEGMENTS@@
    </div>
    <div class="distribution-key" aria-hidden="true">
@@DISTRIBUTION_KEYS@@
    </div>
  </section>

  <nav class="section-jump" id="section-jump" aria-label="Jump to namespace"></nav>
  <div id="namespace-sections"></div>

  <footer>
    <div class="footer-notes">
      <article class="note"><strong>Escalation is policy-routed</strong><p>The scan keeps escalation out of the table; exact escalation lane, profile, and policy remain in the TSV. @@ESCALATION_NOTE@@</p></article>
      <article class="note"><strong>Deny-default lanes are policy-gated</strong><p>A deny-default CLI may only hold a primary where <code>shared/lane-policy.tsv</code> carries an operator-ratified exception — currently @@DENY_DEFAULT_PRIMARIES@@.</p></article>
      <article class="note"><strong>Backup is manual</strong><p>The Backup column is the cross-family option Chrono may use in a new ordinary board packet after an operator decision. Signals may surface an operational failure, but automatic redispatch is unsupported.</p></article>
      <article class="note"><strong>High safety is a quality floor</strong><p>HIGH markers reproduce <code>safety_level: high</code> from the TSV. Packet-level mandatory review is derived separately from validated review triggers.</p></article>
    </div>
    <p class="source-line">Generated from the canonical <code>shared/specialist-runtime-map.tsv</code> by <code>tools/export/build_routing_map.py</code>. Its <code>--check</code> mode enforces byte-for-byte currency in CI.</p>
  </footer>
</main>

<script>
(() => {
  const raw = `
@@RAW_ROWS@@
  `.trim();

  const rows = raw.split("\\n").map(line => {
    const [namespace, specialist, roleClass, safety, primary, backup, review] = line.split("|");
    return { namespace, specialist, roleClass, safety, primary, backup, review };
  });
  const order = @@NAMESPACE_ORDER@@;
  const laneStyle = @@LANE_STYLE_MAP@@;
  const laneLabel = @@LANE_LABEL_MAP@@;
  const chip = (lane, kind) => `<span class="lane-chip ${laneStyle[lane]}" data-kind="${kind}">${laneLabel[lane]}</span>`;
  const escapeText = value => value.replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);

  const jump = document.getElementById("section-jump");
  const container = document.getElementById("namespace-sections");

  order.forEach(namespace => {
    const group = rows.filter(row => row.namespace === namespace);
    const slug = namespace.toLowerCase();
    const link = document.createElement("a");
    link.className = "jump-link";
    link.href = `#${slug}`;
    link.textContent = `${namespace} · ${group.length}`;
    jump.appendChild(link);

    const section = document.createElement("section");
    section.className = "namespace-section";
    section.id = slug;
    section.innerHTML = `
      <div class="namespace-heading">
        <h2>${escapeText(namespace)}</h2>
        <span>${group.length} specialist${group.length === 1 ? "" : "s"}</span>
      </div>
      <div class="table-scroll" tabindex="0" role="region" aria-label="${escapeText(namespace)} routing table">
        <table>
          <caption class="visually-hidden">${escapeText(namespace)} specialist model routing</caption>
          <thead><tr><th scope="col">Specialist</th><th scope="col">Class</th><th scope="col">Primary</th><th scope="col">Backup</th><th scope="col">Review</th></tr></thead>
          <tbody>${group.map(row => `
            <tr>
              <td><div class="specialist-wrap"><span class="specialist">${escapeText(row.specialist)}</span>${row.safety === "high" ? '<span class="safety-pill" title="High safety quality floor">high</span>' : ""}</div></td>
              <td><span class="class-name">${escapeText(row.roleClass)}</span></td>
              <td>${chip(row.primary, "primary")}</td>
              <td>${chip(row.backup, "backup")}</td>
              <td>${chip(row.review, "review")}</td>
            </tr>`).join("")}</tbody>
        </table>
      </div>`;
    container.appendChild(section);
  });
})();
</script>"""


def lane_policies_from(source: Path) -> list[dict[str, str]]:
    """Read the registered routing-lane vocabulary and primary defaults."""
    with source.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        required = {"record_kind", "subject", "value", "notes"}
        missing = sorted(required - set(reader.fieldnames or []))
        if missing:
            raise ValueError(f"{source} is missing required column(s): {', '.join(missing)}")

        lane_order: list[str] = []
        seen_lanes: set[str] = set()
        primary_defaults: dict[str, dict[str, str]] = {}
        for line_number, row in enumerate(reader, 2):
            if None in row:
                raise ValueError(f"{source}:{line_number} has more fields than its header")
            if row["record_kind"] == "vocabulary" and row["subject"] == "route_lane":
                lane = row["value"]
                if not TOKEN.fullmatch(lane):
                    raise ValueError(f"{source}:{line_number} has unsafe route lane {lane!r}")
                if lane in seen_lanes:
                    raise ValueError(f"{source}:{line_number} repeats route lane {lane!r}")
                seen_lanes.add(lane)
                lane_order.append(lane)
            elif row["record_kind"] == "primary_default":
                lane = row["subject"]
                if lane in primary_defaults:
                    raise ValueError(f"{source}:{line_number} repeats primary default for {lane!r}")
                if row["value"] not in {"allow", "deny"}:
                    raise ValueError(f"{source}:{line_number} has unknown primary default")
                primary_defaults[lane] = {
                    "primary_default": row["value"],
                    "notes": row["notes"],
                }

    if not lane_order:
        raise ValueError(f"{source} contains no route_lane vocabulary")
    missing_defaults = sorted(seen_lanes - set(primary_defaults))
    extra_defaults = sorted(set(primary_defaults) - seen_lanes)
    if missing_defaults or extra_defaults:
        details = []
        if missing_defaults:
            details.append(f"missing primary defaults: {', '.join(missing_defaults)}")
        if extra_defaults:
            details.append(f"unregistered primary defaults: {', '.join(extra_defaults)}")
        raise ValueError(f"{source} has inconsistent route-lane policy ({'; '.join(details)})")

    return [
        {"lane": lane, **primary_defaults[lane]}
        for lane in lane_order
    ]


def rows_from(source: Path, valid_lanes: set[str]) -> list[dict[str, str]]:
    """Read and validate the TSV fields represented by the page."""
    with source.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        fieldnames = set(reader.fieldnames or [])
        missing = sorted(REQUIRED_COLUMNS - fieldnames)
        if missing:
            raise ValueError(f"{source} is missing required column(s): {', '.join(missing)}")

        rows: list[dict[str, str]] = []
        seen: set[str] = set()
        for line_number, source_row in enumerate(reader, 2):
            if None in source_row:
                raise ValueError(f"{source}:{line_number} has more fields than its header")
            row = {column: source_row[column] for column in REQUIRED_COLUMNS}
            specialist = row["specialist"]
            if not TOKEN.fullmatch(specialist):
                raise ValueError(f"{source}:{line_number} has unsafe specialist token: {specialist!r}")
            if specialist in seen:
                raise ValueError(f"{source}:{line_number} repeats specialist {specialist!r}")
            seen.add(specialist)

            namespace = row["source_namespace"]
            if namespace not in NAMESPACE_ORDER:
                raise ValueError(f"{source}:{line_number} has unknown namespace {namespace!r}")
            if not TOKEN.fullmatch(row["capability_class"]):
                raise ValueError(f"{source}:{line_number} has unsafe capability class")
            if row["safety_level"] not in {"low", "medium", "high"}:
                raise ValueError(f"{source}:{line_number} has unknown safety level")
            for field in ("primary_lane", "backup_lane", "escalate_lane", "review_lane"):
                if row[field] not in valid_lanes | {"none"}:
                    raise ValueError(
                        f"{source}:{line_number} has unknown {field} value {row[field]!r}"
                    )
            if row["primary_lane"] == "none":
                raise ValueError(f"{source}:{line_number} has no primary lane")
            rows.append(row)

    if not rows:
        raise ValueError(f"{source} contains no specialist rows")

    namespace_rank = {namespace: index for index, namespace in enumerate(NAMESPACE_ORDER)}
    return sorted(rows, key=lambda row: (namespace_rank[row["source_namespace"]], row["specialist"]))


def _code_list(values: list[str]) -> str:
    rendered = [f"<code>{html.escape(value)}</code>" for value in values]
    if not rendered:
        return "none"
    if len(rendered) == 1:
        return rendered[0]
    if len(rendered) == 2:
        return " and ".join(rendered)
    return ", ".join(rendered[:-1]) + f", and {rendered[-1]}"


def _lane_label(lane: str) -> str:
    return lane.replace("_", " ").replace("-", " ").title()


def _lane_cards(lane_policies: list[dict[str, str]], counts: Counter[str]) -> str:
    cards = []
    for policy in lane_policies:
        lane = policy["lane"]
        count = counts[lane]
        note = policy["notes"]
        if policy["primary_default"] == "deny":
            noun = "primary" if count == 1 else "primaries"
            note = f"{note} Current map: {count} allowlisted {noun}."
        cards.append(
            f'        <article class="lane-card {lane}" tabindex="0">\n'
            f'          <div class="lane-top"><span class="lane-name">{_lane_label(lane)}</span>'
            f'<span class="lane-count">{count} primary</span></div>\n'
            f'          <code class="model-id">{lane}</code>\n'
            f'          <div class="lane-note">{html.escape(note)}</div>\n'
            f'        </article>'
        )
    return "\n".join(cards)


def render(rows: list[dict[str, str]], lane_policies: list[dict[str, str]]) -> str:
    total = len(rows)
    primary_counts = Counter(row["primary_lane"] for row in rows)
    namespaces = {row["source_namespace"] for row in rows}
    lanes = [policy["lane"] for policy in lane_policies]

    raw_rows = "\n".join(
        "|".join(
            (
                row["source_namespace"].upper(),
                row["specialist"],
                row["capability_class"],
                row["safety_level"],
                row["primary_lane"],
                row["backup_lane"],
                row["review_lane"],
            )
        )
        for row in rows
    )

    segments = []
    keys = []
    distribution_labels = []
    for lane in lanes:
        label = _lane_label(lane)
        count = primary_counts[lane]
        width = count / total * 100
        segments.append(
            f'      <span class="bar-segment {lane}" style="width:{width:.4f}%"></span>'
        )
        keys.append(
            f'      <span class="key-item {lane}"><i class="key-dot"></i>'
            f'{label} <strong>{count}</strong></span>'
        )
        distribution_labels.append(f'{label} {count}')

    deny_default_primaries = []
    for policy in lane_policies:
        if policy["primary_default"] != "deny":
            continue
        lane = policy["lane"]
        primaries = sorted(row["specialist"] for row in rows if row["primary_lane"] == lane)
        deny_default_primaries.append(f"<code>{html.escape(lane)}</code>: {_code_list(primaries)}")
    cross_escalations = sorted(
        row["specialist"]
        for row in rows
        if row["escalate_lane"] not in {row["primary_lane"], "none"}
    )
    if cross_escalations:
        verb = "uses" if len(cross_escalations) == 1 else "use"
        escalation_note = (
            f"{_code_list(cross_escalations)} currently {verb} a different escalation CLI."
        )
    else:
        escalation_note = "Every current row escalates within its primary CLI."

    replacements = {
        "@@TOTAL@@": str(total),
        "@@NAMESPACE_COUNT@@": str(len(namespaces)),
        "@@LANE_COUNT@@": str(len(lanes)),
        "@@LANE_CARDS@@": _lane_cards(lane_policies, primary_counts),
        "@@DISTRIBUTION_LABEL@@": ", ".join(distribution_labels) + " primary specialists",
        "@@DISTRIBUTION_SEGMENTS@@": "\n".join(segments),
        "@@DISTRIBUTION_KEYS@@": "\n".join(keys),
        "@@ESCALATION_NOTE@@": escalation_note,
        "@@DENY_DEFAULT_PRIMARIES@@": "; ".join(deny_default_primaries) or "none",
        "@@RAW_ROWS@@": raw_rows,
        "@@NAMESPACE_ORDER@@": json.dumps([item.upper() for item in NAMESPACE_ORDER]),
        "@@LANE_STYLE_MAP@@": json.dumps({**{lane: lane for lane in lanes}, "none": "neutral"}),
        "@@LANE_LABEL_MAP@@": json.dumps(
            {**{lane: _lane_label(lane) for lane in lanes}, "none": "None"}
        ),
    }
    rendered = BODY_TEMPLATE
    for marker, value in replacements.items():
        rendered = rendered.replace(marker, value)
    if "@@" in rendered:
        raise ValueError("routing-map template contains an unresolved marker")
    return rendered.rstrip() + "\n"


def replace_generated_section(current: str, generated: str) -> str:
    """Replace the one owned block while preserving the static page shell."""
    if current.count(BEGIN_MARKER) != 1 or current.count(END_MARKER) != 1:
        raise ValueError(
            f"{OUTPUT} must contain exactly one {BEGIN_MARKER!r} and one {END_MARKER!r}"
        )
    prefix, remainder = current.split(BEGIN_MARKER, 1)
    _, suffix = remainder.split(END_MARKER, 1)
    return f"{prefix}{BEGIN_MARKER}\n{generated.rstrip()}\n{END_MARKER}{suffix}"


def atomic_write(target: Path, text: str) -> None:
    """Write, fsync, and rename so readers never observe a partial page."""
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=target.parent,
            prefix=f".{target.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary_path = Path(handle.name)
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, target)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", default=".")
    args = parser.parse_args()

    root = Path(args.root)
    source = root / SOURCE
    lane_policy = root / LANE_POLICY
    target = root / OUTPUT
    try:
        lane_policies = lane_policies_from(lane_policy)
        rows = rows_from(source, {policy["lane"] for policy in lane_policies})
        current = target.read_text(encoding="utf-8")
        expected = replace_generated_section(current, render(rows, lane_policies))
    except (OSError, csv.Error, ValueError) as error:
        print(f"unable to render {OUTPUT}: {error}", file=sys.stderr)
        return 1

    if args.check:
        if current != expected:
            print(
                f"{OUTPUT} is stale; regenerate with "
                "python3 tools/export/build_routing_map.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT} is current ({len(rows)} specialists)")
        return 0

    atomic_write(target, expected)
    print(f"wrote {OUTPUT}: {len(rows)} specialists from {SOURCE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
