#!/usr/bin/env python3
"""Generate the public recommended-toolchain catalog from the private registry.

The private registry (`shared/registries/skill-tool-registry.tsv`) is denied from
the public export: its `verified_state`, `lanes`, `evidence` and `notes` columns
are a census of what *we* have working plus the operational gotchas that cost us
campaigns to learn. Publishing it hands over the arsenal rather than the method.

What an adopter actually needs is the opposite: *which* tools to install for a
given kind of hunting on a given kind of target. That is what this emits --
name, what it is for, which technique class it serves, and which targets it can
analyse. No state, no lanes, no evidence, no notes.

Deterministic: same input registry -> byte-identical output, so the export gate
can treat drift as a real signal rather than noise.

    python3 tools/export/build_public_catalog.py [--check]

`--check` regenerates and diffs without writing, exiting non-zero on drift, so
CI can fail when the catalog falls behind the registry it derives from.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

REGISTRY = Path("shared/registries/skill-tool-registry.tsv")
CATALOG = Path("shared/registries/recommended-toolchain.tsv")

HEADER = ["name", "kind", "purpose", "hunting_type", "target_class"]

# Purposes worth recommending. `content`, `ops` and `connector` describe our own
# operational plumbing and say nothing useful about how to hunt.
PUBLISHED_PURPOSES = {"hunting", "research"}

BANNER = [
    "# Recommended toolchain — what to install, by kind of hunting and kind of target.",
    "#",
    "# Generated by tools/export/build_public_catalog.py. Do not hand-edit.",
    "#",
    "# This is a recommendation, not an inventory. It deliberately carries no",
    "# liveness, lane, evidence or notes column: whether a tool works on OUR",
    "# machine is not a fact about YOUR machine, and a capability is only proven",
    "# by a real invocation returning a real result on real target code.",
    "#",
    "# hunting_type is the technique class a tool serves. Coverage is the thing",
    "# worth measuring: an unused applicable technique class is a gap, and a",
    "# technique that was never run cannot support a claim that nothing is there.",
    "# See tools/coverage-ledger/ for the vocabulary and the evidence signatures.",
]


def rows_from(registry: Path) -> list[list[str]]:
    with registry.open(encoding="utf-8", newline="") as handle:
        source = list(csv.DictReader(handle, delimiter="\t"))
    out = []
    for row in source:
        if (row.get("purpose") or "") not in PUBLISHED_PURPOSES:
            continue
        out.append([
            row["name"],
            row.get("record_kind", "") or "—",
            row["purpose"],
            row.get("hunting_type") or "—",
            row.get("target_class") or "—",
        ])
    return sorted(out, key=lambda r: (r[2], r[3], r[0]))


def render(rows: list[list[str]]) -> str:
    lines = list(BANNER)
    lines.append("\t".join(HEADER))
    lines.extend("\t".join(r) for r in rows)
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the catalog is stale instead of rewriting it")
    parser.add_argument("--root", default=".")
    args = parser.parse_args()

    root = Path(args.root)
    rendered = render(rows_from(root / REGISTRY))
    target = root / CATALOG

    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != rendered:
            print(f"{CATALOG} is stale; regenerate with "
                  f"python3 tools/export/build_public_catalog.py", file=sys.stderr)
            return 1
        print(f"{CATALOG} is current")
        return 0

    target.write_text(rendered, encoding="utf-8")
    published = len(rendered.splitlines()) - len(BANNER) - 1
    print(f"wrote {CATALOG}: {published} recommended tools")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
